### ISSUE TITLE
printLock seems to generate pickle EOFError: Ran out of input in VSCode

### ISSUE THREAD

**Issue by MogwaiNerfHerder** [pvsakith/EbookCrawler#1]
When I remove `printLock = Lock()` and remove all references to printLock in 
`def crawlLinks(threadId, printLock):`
and
`def downloadEbooks(dataQueue, printLock):`
and where they are called, everything runs just fine.

**Comment by sakithb** [comment]
Yeah! the printLock is not implemented yet. You can remove them and the program would run fine. The printlocks are used do the different outputs from different threads won't get jumbled. Btw i don't maintain this repo now.
